services:
  backend_flask:
    build: 
      context: ./backend/flask
      dockerfile: Dockerfile
    command: ["app"]
    container_name: backend_flask
    restart: unless-stopped
    tty: true

  #PHP Service
  backend_laravel:
    build:
      context: ./backend/laravel
      dockerfile: Dockerfile
    container_name: backend_laravel
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: backend_laravel
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ./backend/laravel:/var/www/html/
      - ./backend/laravel/php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - app-network

  frontend:
    stdin_open: true
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./frontend:/var/www/html/
    networks:
      - app-network

  #Nginx Service
  webserver:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "81:80"
    networks:
      - app-network
  
  db:
    image: postgres:13
    restart: always
    container_name: bd  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  
      POSTGRES_DB: site
    ports: ["5429:5432"]  
    volumes:  
      - "./.docker/postgres:/var/lib/postgresql/data"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge