services:
  backend:
    build: ./backend
    env_file: ["./backend/env.dev"]
    volumes:
      - ./backend:/app
    networks:
      - traefik
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/backend`)"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    networks:
      - traefik
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/frontend`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=8081"
networks:
  traefik:
    name: traefik

  web:
    name: web